---
title: WQMCast
timezone: America/New_York
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
email: wqmcradioqc@gmail.com
description: A Queens College Club tha creates videos and podcasts for the student population.
baseurl: 
url: wqmcast.github.io
twitter_username: wqmcradio
theme: minima
plugins:
- jekyll-feed
facebook_username: QueensCollegeRadio
instagram_username: wqmcradioqc
youtube_username: channel/UCuzG0kQW3HVG-SHPWTVDxgw
